# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbc" do
  name "dbc"
  desc "A CLI utility for managing ADBC drivers"
  homepage "https://columnar.tech/dbc"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbc"

  on_macos do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "4b02adb55efb9bfe1fd4a6a520c95f9a88a831b663b115402711fd7077c6a818"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "35c0f7fcd83ab111911e7c001bc4095d245c895c06f55109e9cd82fe16a71090"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "5d4ca5ea9b0e5246f90133bab6a5896264b9d70bc304a25ff064868cec414e10"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "fda8f32e91367e8f7d8e9281cc49bd5c34b98ce22a007b83ffd901c59e024e45"
    end
  end

  # No zap stanza required
end
