# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbc" do
  name "dbc"
  desc "The command line tool for installing and managing ADBC drivers"
  homepage "https://columnar.tech/dbc"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbc"
  bash_completion "cmd/dbc/completions/dbc.bash"
  zsh_completion "cmd/dbc/completions/dbc.zsh"
  fish_completion "cmd/dbc/completions/dbc.fish"

  on_macos do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "3bccd0d0f5956ec9f488b60337636137de70f9547a79aea234e334d73ae82df0"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "ac02c37555b8d5185c2f57eb1f2772c161a304d819d1fc1fe56137f77205398d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "bca1737bedde571b05768ed4c53c7ff318ba8303d359af24440d1c36dc5262e8"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "afae5b706f09b17785ba34f0564e5585eaae656f2539a4bf012713d90fde2922"
    end
  end

  # No zap stanza required
end
