# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbc@0.3.1" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "c7528a710bb4e4551681e322724cb0d9d656d913f4837f566b4ac5fdb90a7a15"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-arm64-#{version}.tar.gz",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_intel do
      sha256 "1574c825122b2d4096cd17daa535ca151675fde499b976bb7f5c56425b149fe6"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-amd64-#{version}.tar.gz",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end
  on_linux do
    on_arm do
      sha256 "1a875bb6b1c76c83141a6a3aa0ce8510b1715c220ddbe88399377871abbe6982"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-arm64-#{version}.tar.gz",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_intel do
      sha256 "d394fe15226c3db4a980568f2b3aff049c58ef2badea6cbb711bc4cf3b7b2ed7"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-amd64-#{version}.tar.gz",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "dbc@0.3.1"
  desc "The command line tool for installing and managing ADBC drivers"
  homepage "https://columnar.tech/dbc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbc"
  bash_completion "dbc.bash"
  fish_completion "dbc.fish"
  zsh_completion "dbc.zsh"

  # No zap stanza required
end
