# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbc@0.0" do
  name "dbc@0.0"
  desc "A CLI utility for managing ADBC drivers"
  homepage "https://columnar.tech/dbc"
  version "0.0.1-beta3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbc"

  on_macos do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/downloadv#{version}/dbc-darwin-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "f00c04477c10997f48c483d95e1ebf17785ae0e7e9fb3b5ad1a9144148768b75"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/downloadv#{version}/dbc-darwin-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "796c8299da0f0e8095343611db116852895dda6c4018ea08eb22d79e3c30ad11"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/downloadv#{version}/dbc-linux-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "32840ca901e6e0cfd8af8486d2f405a3e40df350fa6e4d087f179851ba7b2605"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/downloadv#{version}/dbc-linux-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        using: :homebrew_curl,
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "272d1be1fb3b31830c3ef448b05748ad223637d7a522d90746fd84987bd1ec48"
    end
  end

  # No zap stanza required
end
