# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbc@0.2.0-beta1" do
  name "dbc@0.2.0-beta1"
  desc "A CLI utility for managing ADBC drivers"
  homepage "https://columnar.tech/dbc"
  version "0.2.0-beta1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbc"

  on_macos do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "282fbee5ef5b35cc1e3ede77ba6b1a4050fa7fd64606470059dab24ea197c4d1"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "9a77bf44156bbac15b1b86f5b62e5697a192f3568c396c20172a9ffb092e8d1b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "b5f11e2787344fcf3562803e9a2ae88bc77118919a4eea3d943ed5c158814f8c"
    end
    on_arm do
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
      sha256 "b76952a8194f8c48bb2b6205fa19d5147ceddacdf7f43088d94fde79f2ef1a86"
    end
  end

  # No zap stanza required
end
