# This file was generated by GoReleaser. DO NOT EDIT.
cask "dbc@0.3" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "bce26e38d3930c8f6225c506b6815f1a5f7f1c8b7d8d93c6b6a2bf89338cd3b8"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "a4a176f1ef3e29af02050239376b06f4e1b5ea0d014eb6130af11ffd76e4cb2b"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-darwin-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  on_linux do
    on_intel do
      sha256 "bb575a9f522062a122fce417de29489d8c7b2c2fb415e3ef9eb8a0c4147b6270"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-amd64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
    end
    on_arm do
      sha256 "0fa2993f57e22fd0e6aa4c123868cb903bb59ff117498746c3b2b0f0ed484f64"
      url "https://github.com/columnar-tech/dbc/releases/download/v#{version}/dbc-linux-arm64-#{version}.tar.gz",
        verified: "github.com/columnar-tech/dbc/",
        cookies: {
          "license" => "accept-backup",
        }
    end
  end

  name "dbc@0.3"
  desc "The command line tool for installing and managing ADBC drivers"
  homepage "https://columnar.tech/dbc"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dbc"
  bash_completion "dbc.bash"
  fish_completion "dbc.fish"
  zsh_completion "dbc.zsh"

  # No zap stanza required

end
